### PR TITLE
fix: use increase allowance instead of deprecated approve

### PR DESCRIPTION
**Pull request by Dev-Doggo**
Closes: truflation/truf-claim-page#232

### CODE REVIEW

**Review by lewis999bits — CHANGES_REQUESTED** [review]
@Dev-Doggo I guess there are more functions used that should be replaced

**Comment by Dev-Doggo** [comment]
> @Dev-Doggo I guess there are more functions used that should be replaced

@lewis999bits What functions?

**Comment by lewis999bits** [comment]
F.e https://github.com/truflation/truflation-contracts/blob/010448ea069c0a1b762104a75aad345219c3f96e/src/TrufPartner.sol#L136

**Comment by Dev-Doggo** [comment]
> F.e
> 
> https://github.com/truflation/truflation-contracts/blob/010448ea069c0a1b762104a75aad345219c3f96e/src/TrufPartner.sol#L136

That doesn't exist on main branch

**Review by lewis999bits — APPROVED** [review]

**Pull request merged**
