### PR TITLE
fix: "pay" function maximum allowance

### PR DESCRIPTION
**Pull request by Dev-Doggo**
Closes: truflation/truf-claim-page#220

### CODE REVIEW

**Comment by Dev-Doggo** [comment]
@markholdex We have another approach to solve this which would make the user calls cheaper. Basically the `uniV2Router`, `trufToken`, `pairToken`, `lpToken` are all immutables so we could set approval for max value (`type(uint256).max`) in the constructor and avoid having to use any kind of additional approval calls in any other functions, let me know your thoughts

cc: @zolotokrylin

**Comment by markholdex** [comment]
@Dev-Doggo isn't the allowance individual for each address? How would constructor help in this case?

**Comment by Dev-Doggo** [comment]
> @Dev-Doggo isn't the allowance individual for each address? How would constructor help in this case?

Yeah it is, but as we know what the tokens that will require any kind of approval in the constructor we can immediately set the allowances for the router to the max value

**Comment by markholdex** [comment]
@Dev-Doggo how is it different from what the auditor suggest? And what is the utility of the TrufPartner contract because we haven't used that in the interface anywhere yet.

**Comment by Dev-Doggo** [comment]
> @Dev-Doggo how is it different from what the auditor suggest? And what is the utility of the TrufPartner contract because we haven't used that in the interface anywhere yet.

I'm not sure what each contract is used for, I didn't work on the contracts.
The difference from what the auditor suggested is that it's cheaper for the user calling the `pay` function

**Comment by markholdex** [comment]
@Dev-Doggo but isn't there a *risk that once the limit is reached, the approvals won't work anymore?

**Comment by Dev-Doggo** [comment]
> @Dev-Doggo but isn't there a *risk that once the limit is reached, the approvals won't work anymore?

The max number is so large that by the time that time comes the universe won't be around anymore 😂

**Comment by markholdex** [comment]
@Dev-Doggo seems ok for me to go either way for now. Take the decision and let me know when to review.

**Comment by Dev-Doggo** [comment]
> @Dev-Doggo seems ok for me to go either way for now. Take the decision and let me know when to review.

You can review it now

**Review by markholdex — APPROVED** [review]

**Pull request merged**
